### ISSUE TITLE
Add delay to commands?

### ISSUE THREAD

**Issue by DennisMadsen** [dpjanes/homestar-denon-avr#1]
If I turn off my receiver and push multiple commands in one push to my Denon AVR-X1100W, only the turn on command is executed. Like:

    bridge.push({
        on: true,
        volume: 0.5,
        band: 'AUX1'
    });

It seems that while powering on the AVR, the following volume and band commands are ignored. Should there we some kind of delay between commands send to the AVR?

**Comment by dpjanes** [comment]
Looking at this. I should be able to handle this under the queuing system, ensuring that it's in power on state before sending any other commands

**Comment by DennisMadsen** [comment]
That sounds like the way to go. I've tested volume, band and sound_mode in one push without any issues. Nice if your queuing system can handle that.

Related to this, the push function is implemented so that a PWON command is sent after every other command set. Maybe that isn't necessary if the device is already powered on. Furthermore the PWON is sent after the other commands. Maybe the AVR should be PWON before sending the other commands?

Maybe the PWON/PWSTANDBY command should only be sent, if the pushd input parameter has the "on" key (boolean)?

**Comment by dpjanes** [comment]
It took a bit of work but this should be in there.

Note that I assume that sending any command (except on:false) wants to turn on the device. I had to implement two different types of delays: 
- one for initially figuring out the initial on/off state of the device
- another if we just turned on the device (this one 10 seconds) before sending other commands

**Comment by dpjanes** [comment]
Please close if you're happy

**Comment by dpjanes** [comment]
Any luck?

**Comment by DennisMadsen** [comment]
I've been testing it and it seems to work now :)

Nice work!
