### ISSUE TITLE
Require the module has double .Bridge reference

### ISSUE THREAD

**Issue by DennisMadsen** [dpjanes/homestar-denon-avr#2]
If I install this using "npm install homestar-denon-avr --save" into my project and e.g. include the "connect_mdns.js" sample to test it, I have to require the DenonAVRBridge  in this way:

    var DenonAVRBridge = require('homestar-denon-avr').Bridge.Bridge;

Is there something wrong with the index.js?

	/*
	 *  NOTE: prefer to do the way 'model.js' works
	 *  Connect to a Denon AVR by searching MDNS/Bonjour
	 */

	var DenonAVRBridge = require('homestar-denon-avr').Bridge.Bridge;

	var denon = new DenonAVRBridge({
	    mdns: true,
	});
	denon.discovered = function(bridge) {
	    console.log("+ got one", bridge.meta());
	    bridge.pulled = function(state) {
	        console.log("+ state-change", state);
	    };
	    bridge.connect();
	    bridge.push({
	        volume: .5,
	    });
	};
	denon.discover();

**Comment by dpjanes** [comment]
There's an issue in index.js. Fixing now.

**Comment by dpjanes** [comment]
This should be fixed

**Comment by dpjanes** [comment]
Please close after you confirm.

**Comment by DennisMadsen** [comment]
Thank you.

**Comment by dpjanes** [comment]
Actually had the same error in a bunch of my other homestar-* modules. Bad prototype directory.
