### ISSUE TITLE
Discover error ECONNREFUSED

### ISSUE THREAD

**Issue by dennismadsen** [dpjanes/homestar-denon-avr#7]
I'm facing some issues when running on my Raspberry PI.

Here is the sample application I'm running:
![image](https://cloud.githubusercontent.com/assets/295606/7441559/6106827e-f0ed-11e4-8c60-79e5d3d1a791.png)

After it has run for some time, I do not know exactly how long but maybe an hour, I start to see a this error:
![unnamed](https://cloud.githubusercontent.com/assets/295606/7441562/6c26afd0-f0ed-11e4-8acf-a956052d9eab.png)

It's fired quite often, around 20-30 times pr. second. 10.0.1.5 is the IP of my Denon device.

**Comment by dpjanes** [comment]
I bet the problem is with the MDNS discovery. Will investigate. I assume it's using the "kludge" code path?

**Comment by dennismadsen** [comment]
I thought that the MDNS discovery was disabled on Raspberry PI?

**Comment by dpjanes** [comment]
Yes, but you had a fix I believe that you submitted?

**Comment by dpjanes** [comment]
I've made a change to the MDNS hack that I'm hoping will fix this. If you update this module, you should get it. Let me know how it goes.

**Comment by dennismadsen** [comment]
Sorry, but that doesn't help. I've a npm module has these dependencies:
- homestar-denon-avr 0.0.15
- iotdb 0.6.7

You can download my small demo-example here: http://www.megafileupload.com/12s8/denon-test.zip. Note that the test.js is a copy from the sample-folder of this project.

I start to receive the ECONNREFUSED errors just a minutes after the device is connected:

    dhrm@raspberrypi ~/denon-test $ node test.js 
    *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
    *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"discover","error":{"code":-3008,"errno":-3008,"syscall":"getaddrinfo"},"cause":"likely network related - ignoring","msg":"error","time":"2015-05-06T15:38:52.716Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":40,"msg":"switching to avahi-mdns-kludge","time":"2015-05-06T15:38:52.755Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"discover","error":{"code":-3008,"errno":-3008,"syscall":"getaddrinfo"},"cause":"likely network related - ignoring","msg":"error","time":"2015-05-06T15:38:52.839Z","v":0}
    + got one { 'iot:thing': 'urn:iotdb:thing:DenonAVR:Home-Theater.local:19d0dff6264711dd29943d563825f8fe',
      'schema:name': 'Home-Theater.local',
      'schema:manufacturer': 'http://www.denon.com/' }
    + state-change { volume: 0.566 }
    + state-change { volume: 0.566, band: 'TV' }
    + state-change { volume: 0.566, band: 'TV', on: false }
    + state-change { volume: 0.566, band: 'TV', on: true }
    + state-change { volume: 0.5, band: 'TV', on: true }
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T15:39:54.315Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T15:40:09.313Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T15:40:24.313Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11284,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T15:40:39.316Z","v":0}

**Comment by dpjanes** [comment]
Ah, I think maybe it's "retry" code which isn't supposed to be used when
it's in MDNS mode. Try now.

D

**Comment by dennismadsen** [comment]
I'm still getting that error after updating. I'm still getting the state-change, but not it seems that the error is happening every minute.

    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11875,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T17:40:32.376Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11875,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T17:41:33.461Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11875,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T17:42:34.576Z","v":0}
    {"name":"homestar-denon-avr","module":"DenonAVRBridge","hostname":"raspberrypi","pid":11875,"level":50,"method":"_discover_host/_on_error","host":"10.0.1.5","port":23,"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"},"msg":"error","time":"2015-05-06T17:43:35.637Z","v":0}

**Comment by dpjanes** [comment]
Yes, I'm expecting that. I might clean it up when I have a little more
time, basically it would be tracking what's already connected and not doing
it again.

D.

**Comment by dennismadsen** [comment]
Thank you. I'm closing this for now.
